language: haskell
install:
  - npm install -g elm
  - elm-package install -y
cache:
  directories:
    - elm-stuff/build-artifacts
before_script: 
  - elm-make --yes --output test.js tests/RomansTests.elm
script: node test.js
